### ISSUE TITLE
Capture "Up Arrow" and "Down Arrow" key presses

### ISSUE THREAD

**Issue by shivanshu3** [ibigbug/PowerSession#11]
Up and down arrow key presses are useful for going through your command line history.

(Thank you so much for creating this BTW. It was really useful for me to learn how ConPTY works.)

**Comment by ibigbug** [comment]
@shivanshu3 sounds good idea. `Console.ReadKey` doesn't gives the KeyCode for Arrow keys hence need to handle them manually. there should be more special keys to be handled, though only finished 4 of them in this PR. please try the latest release 1.4.0

**Comment by shivanshu3** [comment]
Thank you!
