### ISSUE TITLE
Recorder should not capture all environment vars

### ISSUE THREAD

**Issue by ariasemis** [ibigbug/PowerSession#9]
Thank you for making this, it's really awesome!

I noticed that the output file lists all my `env` variables, which is not ideal when sharing it.

According to the spec from [asciicinema](https://github.com/asciinema/asciinema/blob/master/doc/asciicast-v2.md):

> Official asciinema recorder captures only `SHELL` and `TERM` by default. All implementations of asciicast-compatible terminal recorder should not capture any additional environment variables unless explicitly permitted by the user.

Do you think this could be fixed?

Thank you again!!

**Comment by comnam90** [comment]
It would be good to get this issue addressed

**Comment by ibigbug** [comment]
thanks for the contribution!

release created: https://github.com/ibigbug/PowerSession/releases/tag/release-1.3.0
